name: Dependency Updates

on:
  schedule:
    - cron: '0 8 * * *' # Every day at 8 AM UTC
  workflow_dispatch:

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Check for outdated packages
        run: npm outdated || true

      - name: Update Playwright
        run: |
          npm update @playwright/test playwright
          npx playwright install

      - name: Run tests with updated dependencies
        run: npx playwright test --project=chromium

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        if: success()
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: update dependencies'
          title: 'Automated dependency updates'
          body: |
            This PR contains automated dependency updates.
            
            - Updated Playwright and related packages
            - Tests passed with updated dependencies
          branch: dependency-updates
          delete-branch: true
